def ACCTest(String label, String compiler, String unit, String suite) {
    def c_compiler
    def cpp_compiler
    stage("$label $compiler $unit $suite") {
        node("$label") {
            cleanWs()
            checkout scm

            timeout(15) {
                dir('build') {
                    if (compiler == "gcc") {
                        c_compiler = "gcc"
                        cpp_compiler = "g++"
                    } else if (compiler == "clang-7") {
                        c_compiler = "clang-7"
                        cpp_compiler = "clang++-7"
                    }
                    withEnv(["CC=${c_compiler}","CXX=${cpp_compiler}"]) {
                        sh """
                        cmake .. -DCMAKE_BUILD_TYPE=${suite}
                        make
                        ctest --output-on-failure
                        """
                    }
                }
            }

        }
    }
}

def simulationTest(String compiler, String unit, String suite ) {
    def c_compiler
    def cpp_compiler
    stage("Sim $compiler $unit $suite") {
        node {
            cleanWs()
            checkout scm

            def oetoolsSim = docker.build("oetools-simulation", "-f .jenkins/Dockerfile .")
            oetoolsSim.inside {
                timeout(15) {
                    dir('build') {
                        if (compiler == "gcc") {
                            c_compiler = "gcc"
                            cpp_compiler = "g++"
                        } else if (compiler == "clang-7") {
                            c_compiler = "clang-7"
                            cpp_compiler = "clang++-7"
                        }
                        withEnv(["CC=${c_compiler}","CXX=${cpp_compiler}","OE_SIMULATION=1"]) {
                            sh """
                            cmake .. -DCMAKE_BUILD_TYPE=${suite} -DUSE_LIBSGX=OFF
                            make
                            ctest --output-on-failure
                            """
                        }
                    }
                }
            }
        }
    }
}

def ACCContainerTest(String label) {
    stage("$label Container RelWithDebInfo") {
        node("$label") {
            cleanWs()
            checkout scm

            def oetoolsContainer = docker.build("oetools-containertest", "-f .jenkins/Dockerfile .")
            oetoolsContainer.inside('--device /dev/sgx:/dev/sgx') {
                timeout(15) {
                    dir('build') {
                        withEnv(["CC=clang-7","CXX=clang++-7"]) {
                            sh """
                            cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
                            make
                            ctest --output-on-failure
                            """
                        }
                    }
                }
            }
        }
    }
}

def checkDevFlows() {
    stage('Check dev flows') {
        node {
            cleanWs()
            checkout scm

            def oetoolsCheck = docker.build("oetools-check", "-f .jenkins/Dockerfile .")
            oetoolsCheck.inside {
                timeout(2) {
                    sh './scripts/check-ci'
                }
            }
        }
    }
    stage('Default compiler') {
        // This stage verifies developer flows after running ansible playbooks to bootstrap a machine.
        node {
            cleanWs()
            checkout scm

            def buildImage = docker.build("oetools-base", '-f .jenkins/Dockerfile.scripts .')

            buildImage.inside {
                timeout(15) {
                    // This is run to test that it works with the dependencies
                    // installed by our install-prereqs ansible playbook.

                    dir('build') {
                        sh '''
                        cmake .. -DUSE_LIBSGX=OFF
                        make
                    '''
                        // Note that `make package` is not expected to work
                        // without extra configuration.
                    }
                }
            }
        }
    }
}

def win2016DebugLinuxElfBuild() {
    stage('Linux SGX1 Debug') {
        node {
            cleanWs()
            checkout scm
            def oetoolsWincp = docker.build("oetools-wincp", "-f .jenkins/Dockerfile .")
            oetoolsWincp.inside {
                timeout(15) {
                    dir('build') {
                        withEnv(["CC=clang-7","CXX=clang++-7"]) {
                            sh """
                            cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_DEBUG_MALLOC=OFF
                            make
                            """
                        }
                    }
                    stash includes: 'build/tests/**', name: 'linuxdebug'
                }
            }
        }
    }
    stage('Windows Debug') {
        node('SGXFLC-Windows') {
            cleanWs()
            checkout scm
            unstash 'linuxdebug'
            bat 'move build linuxbin'
            dir('build') {
                bat "vcvars64.bat x64 && cmake.exe -G \"Visual Studio 15 2017 Win64\" -DADD_WINDOWS_ENCLAVE_TESTS=1 -DCMAKE_BUILD_TYPE=Debug -DLINUX_BIN_DIR=${WORKSPACE}\\linuxbin\\tests .. && msbuild ALL_BUILD.vcxproj -p:Configuration=Debug && ctest.exe -V -C Debug"
            }
       }
    }
}

def win2016ReleaseLinuxElfBuild() {
    stage('Linux SGX1 Release') {
        node {
            cleanWs()
            checkout scm
            def oetoolsWin = docker.build("oetools-wincp", "-f .jenkins/Dockerfile .")
            oetoolsWin.inside {
                timeout(15) {
                    dir('build') {
                        withEnv(["CC=clang-7","CXX=clang++-7"]) {
                            sh """
                            cmake .. -DCMAKE_BUILD_TYPE=Release
                            make
                            """
                        }
                    }
                    stash includes: 'build/tests/**', name: 'linuxrelease'
                }
            }
        }
    }
    stage('Windows Release') {
        node('SGXFLC-Windows') {
            cleanWs()
            checkout scm
            unstash 'linuxrelease'
            bat 'move build linuxbin'
            dir('build') {
                bat "vcvars64.bat x64 && cmake.exe -G \"Visual Studio 15 2017 Win64\" -DADD_WINDOWS_ENCLAVE_TESTS=1 -DCMAKE_BUILD_TYPE=Release -DLINUX_BIN_DIR=${WORKSPACE}\\linuxbin\\tests .. && msbuild ALL_BUILD.vcxproj -p:Configuration=Release && ctest.exe -V -C Release"
            }
        }
    }
}

def win2016DebugCrossCompile() {
    stage('Windows Debug') {
        node('SGXFLC-Windows') {
            cleanWs()
            checkout scm
            dir('build') {
                withEnv(["CC=cl.exe","CXX=cl.exe"]) {
                    bat "vcvars64.bat x64 && cmake.exe -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_ENCLAVES=1 .. && ninja.exe && ctest.exe -V -C Debug"
                }
            }
       }
    }
}

def win2016ReleaseCrossCompile() {
    stage('Windows Release') {
        node('SGXFLC-Windows') {
            cleanWs()
            checkout scm
            dir('build') {
                withEnv(["CC=cl.exe","CXX=cl.exe"]) {
                    bat "vcvars64.bat x64 && cmake.exe -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_ENCLAVES=1 .. && ninja.exe && ctest.exe -V -C Release"
                }
            }
        }
    }
}
parallel "Check Developer Experience" :         { checkDevFlows() },
        "Sim clang-7 SGX1 Debug" :              { simulationTest('clang-7', 'SGX1', 'Debug')},
        "Sim clang-7 SGX1 Release" :            { simulationTest('clang-7', 'SGX1', 'Release')},
        "Sim clang-7 SGX1 RelWithDebInfo" :     { simulationTest('clang-7', 'SGX1', 'RelWithDebInfo')},
        "Sim clang-7 SGX1-FLC Debug" :          { simulationTest('clang-7', 'SGX1FLC', 'Debug')},
        "Sim clang-7 SGX1-FLC Release" :        { simulationTest('clang-7', 'SGX1FLC', 'Release')},
        "Sim clang-7 SGX1-FLC RelWithDebInfo" : { simulationTest('clang-7', 'SGX1FLC', 'RelWithDebInfo')},
        "ACC1604 clang-7 Debug" :               { ACCTest('ACC-1604', 'clang-7', 'SGX1FLC', 'Debug') },
        "ACC1604 clang-7 Release" :             { ACCTest('ACC-1604', 'clang-7', 'SGX1FLC','Release') },
        "ACC1604 clang-7 RelWithDebInfo" :      { ACCTest('ACC-1604', 'clang-7', 'SGX1FLC', 'RelWithDebinfo') },
        "ACC1604 gcc Debug" :                   { ACCTest('ACC-1604', 'gcc', 'SGX1FLC', 'Debug') },
        "ACC1604 gcc Release" :                 { ACCTest('ACC-1604', 'gcc', 'SGX1FLC', 'Release') },
        "ACC1604 gcc RelWithDebInfo" :          { ACCTest('ACC-1604', 'gcc', 'SGX1FLC', 'RelWithDebInfo') },
        "ACC1804 clang-7 Debug" :               { ACCTest('ACC-1804', 'clang-7', 'SGX1FLC', 'Debug') },
        "ACC1804 clang-7 RelWithDebInfo" :      { ACCTest('ACC-1804', 'clang-7', 'SGX1FLC', 'RelWithDebinfo') },
        "Win2016 Debug Cross Compile" :         { win2016DebugCrossCompile() },
        "Win2016 Release Cross Compile" :       { win2016ReleaseCrossCompile() },
        "Win2016 Debug Linux-Elf-build" :       { win2016DebugLinuxElfBuild() },
        "Win2016 Release Linux-Elf-build" :     { win2016ReleaseLinuxElfBuild() },
        "ACC1604 Container RelWithDebInfo" :    { ACCContainerTest('ACC-1604') }
